### ISSUE TITLE
update for pg-promise 2.x

### ISSUE THREAD

**Issue by vitaly-t** [radify/collimator#34]
Following the code in this file: https://github.com/radify/collimator/blob/master/src/util/fileQuery.js

```js
resultMask = resultMask || global.queryResult.manyOrNone;
```

It won't work with pg-promise 2.x, because of a breaking change, see [queryResult is no longer global](https://github.com/vitaly-t/pg-promise/wiki/2.0-Migration#3-queryresult-is-no-longer-global)

**Comment by warrenseymour** [comment]
Thanks for the heads-up Vitaly, I'll get a fix out for this today.
